# 📘 Session 7: NumPy Fundamentals
### Duration: ~3.5 Hours

---

**Topics Covered:**
1. NumPy Arrays — Creating and understanding ndarrays
2. Indexing and Slicing — Accessing array elements
3. Array Operations — Vectorization and element-wise operations
4. Broadcasting — Operating on arrays of different shapes
5. Linear Algebra Basics — Dot products, matrix operations
6. Common Data Science Operations

---

**Why This Session Matters for Data Science:**
- **NumPy is the foundation** — All Python data science builds on NumPy arrays
- **Performance** — 100-1000x faster than Python lists for numerical operations
- **Pandas uses NumPy** — DataFrames are built on NumPy arrays underneath
- **Machine Learning** — Scikit-Learn, TensorFlow, PyTorch all use NumPy arrays
- **Vectorization** — Write fast code without explicit loops
- **Broadcasting** — Elegant way to operate on arrays of different shapes

> NumPy is non-negotiable for data science. Every ML practitioner must master it. This is where we move from "Python basics" to "actual data science."

---
## 1. NumPy Arrays — The Fundamental Data Structure

**NumPy** (Numerical Python) provides `ndarray` (n-dimensional array) — the core data structure for numerical computing.

### Why NumPy Arrays Instead of Lists?

| Feature | Python List | NumPy Array |
|---------|------------|------------|
| Speed | Slow (interpreted) | **Fast (compiled C)** |
| Memory | High (stores type info) | **Low (fixed type)** |
| Homogeneity | Mixed types | **One type only** |
| Operations | Element-by-element loops | **Vectorized (no loops)** |
| Math | Manual or NumPy | **Built-in functions** |
| Use Case | General Python | **Numerical computing** |

### Creating Arrays

```python
import numpy as np

# From list
arr = np.array([1, 2, 3, 4, 5])

# Sequences
np.arange(0, 10, 2)        # 0, 2, 4, 6, 8
np.linspace(0, 1, 5)       # 5 evenly spaced values from 0 to 1

# Special arrays
np.zeros(5)                # [0., 0., 0., 0., 0.]
np.ones((2, 3))            # 2×3 array of ones
np.eye(3)                  # 3×3 identity matrix
np.random.rand(3, 3)       # 3×3 random numbers [0, 1)
```

### Array Properties

| Property | Meaning | Example |
|----------|---------|----------|
| `shape` | Dimensions | `(3, 4)` for 3×4 array |
| `dtype` | Data type | `int32`, `float64`, `bool` |
| `size` | Total elements | 12 for 3×4 array |
| `ndim` | Number of dimensions | 1D=1, 2D=2, etc. |

> ⚠️ **Special Case — Arrays have fixed type**: `arr = np.array([1, 2, 3])` creates `int64`. Adding `arr.append(1.5)` will truncate to `int`. Use `astype()` to convert: `arr.astype(float)`.

> ⚠️ **Special Case — Copy vs View**: `arr2 = arr` doesn't copy; they share data! Use `arr.copy()` to create independent copy.

> **Data Science relevance**: Pandas DataFrames have `.values` that returns NumPy arrays. Everything downstream uses NumPy arrays.

In [12]:
# --- Creating NumPy Arrays ---
import numpy as np

print(f"NumPy version: {np.__version__}")

# From list
arr1 = np.array([1, 2, 3, 4, 5])
print(f"\nFrom list: {arr1}")
print(f"  Shape: {arr1.shape}, dtype: {arr1.dtype}, size: {arr1.size}")

# arange (like range but returns array)
arr2 = np.arange(0, 10, 2)
print(f"\narange(0, 10, 2): {arr2}")

# linspace (evenly spaced)
arr3 = np.linspace(0, 1, 5)
print(f"\nlinspace(0, 1, 5): {arr3}")

# zeros and ones
zeros = np.zeros(3)
ones = np.ones((2, 3))
print(f"\nzeros(3): {zeros}")
print(f"ones((2, 3)):\n{ones}")

# Identity matrix
identity = np.eye(3)
print(f"\neye(3) - identity matrix:\n{identity}")

# Random
random_arr = np.random.rand(2, 3)
print(f"\nrandom.rand(2, 3):\n{random_arr}")

NumPy version: 2.4.4

From list: [1 2 3 4 5]
  Shape: (5,), dtype: int64, size: 5

arange(0, 10, 2): [0 2 4 6 8]

linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]

zeros(3): [0. 0. 0.]
ones((2, 3)):
[[1. 1. 1.]
 [1. 1. 1.]]

eye(3) - identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

random.rand(2, 3):
[[0.28203457 0.17743954 0.75061475]
 [0.80683474 0.99050514 0.41261768]]


In [13]:
# --- 2D Arrays (Matrices) ---
import numpy as np

# Create 2D array
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matrix:")
print(matrix)
print(f"Shape: {matrix.shape}")
print(f"ndim: {matrix.ndim}")
print(f"size: {matrix.size}")

# Reshape
reshaped = np.arange(12).reshape(3, 4)
print(f"\nReshaped (3, 4):\n{reshaped}")

# Flatten (convert to 1D)
flattened = reshaped.flatten()
print(f"\nFlattened: {flattened}")

# Type checking
print(f"\nType of matrix: {type(matrix)}")
print(f"Element type: {matrix.dtype}")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
ndim: 2
size: 9

Reshaped (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Type of matrix: <class 'numpy.ndarray'>
Element type: int64


---
## 2. Indexing and Slicing

NumPy indexing is similar to lists, but more powerful with multi-dimensional support.

### 1D Indexing

```python
arr = np.array([10, 20, 30, 40, 50])

arr[0]           # 10 (first element)
arr[-1]          # 50 (last element)
arr[1:4]         # [20, 30, 40] (slice)
arr[::2]         # [10, 30, 50] (every 2nd element)
arr[::-1]        # [50, 40, 30, 20, 10] (reverse)
```

### 2D Indexing

```python
matrix = np.array([[1, 2, 3], [4, 5, 6]])

matrix[0]        # [1, 2, 3] (first row)
matrix[0, 1]     # 2 (row 0, col 1)
matrix[:, 0]     # [1, 4] (first column)
matrix[0, :]     # [1, 2, 3] (first row — same as matrix[0])
matrix[0:1, 1:3] # [[2, 3]] (first row, cols 1-2)
```

### Boolean Indexing (Filtering)

```python
arr = np.array([1, 2, 3, 4, 5])

mask = arr > 2          # [False, False, True, True, True]
arr[mask]               # [3, 4, 5]
arr[arr > 2]            # [3, 4, 5] (same, one-liner)
```

> ⚠️ **Special Case — Slices return views, not copies**: `slice = arr[1:3]` shares data with `arr`. Changes to `slice` affect `arr`! Use `arr[1:3].copy()` to avoid this.

> ⚠️ **Special Case — 2D indexing order**: Always `[row, col]`, not `[col, row]`.

In [14]:
# --- Indexing and Slicing ---
import numpy as np

# 1D indexing
arr = np.array([10, 20, 30, 40, 50])
print(f"Array: {arr}")
print(f"arr[0]: {arr[0]}")
print(f"arr[-1]: {arr[-1]}")
print(f"arr[1:4]: {arr[1:4]}")
print(f"arr[::2] (every 2nd): {arr[::2]}")
print(f"arr[::-1] (reversed): {arr[::-1]}")

# 2D indexing
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f"\nMatrix:\n{matrix}")
print(f"\nmatrix[0]: {matrix[0]}")
print(f"matrix[0, 1]: {matrix[0, 1]}")
print(f"matrix[:, 0]: {matrix[:, 0]}")
print(f"matrix[1:3, 1:3]:\n{matrix[1:3, 1:3]}")

# Boolean indexing
print(f"\n--- Boolean Indexing ---")
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr > 3
print(f"arr: {arr}")
print(f"mask (arr > 3): {mask}")
print(f"arr[mask]: {arr[mask]}")
print(f"arr[arr % 2 == 0] (even): {arr[arr % 2 == 0]}")

Array: [10 20 30 40 50]
arr[0]: 10
arr[-1]: 50
arr[1:4]: [20 30 40]
arr[::2] (every 2nd): [10 30 50]
arr[::-1] (reversed): [50 40 30 20 10]

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

matrix[0]: [1 2 3]
matrix[0, 1]: 2
matrix[:, 0]: [1 4 7]
matrix[1:3, 1:3]:
[[5 6]
 [8 9]]

--- Boolean Indexing ---
arr: [1 2 3 4 5 6]
mask (arr > 3): [False False False  True  True  True]
arr[mask]: [4 5 6]
arr[arr % 2 == 0] (even): [2 4 6]


---
## 3. Array Operations — Vectorization

**Vectorization** means applying operations to entire arrays without explicit loops. This is both cleaner and **much faster**.

### Element-wise Operations

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b            # [5, 7, 9]
a - b            # [-3, -3, -3]
a * b            # [4, 10, 18]  — element-wise multiply, NOT matrix multiply
a / b            # [0.25, 0.4, 0.5]
a ** 2           # [1, 4, 9]  — element-wise power
np.sqrt(a)       # [1.0, 1.414..., 1.732...]
```

### Aggregation Functions

| Function | Description | Example |
|----------|-------------|----------|
| `np.sum()` | Sum all elements | `np.sum(arr)` |
| `np.mean()` | Average | `np.mean(arr)` |
| `np.std()` | Standard deviation | `np.std(arr)` |
| `np.min()`, `np.max()` | Min/max | `np.min(arr)` |
| `np.argmin()`, `np.argmax()` | Index of min/max | `np.argmax(arr)` |
| `np.cumsum()` | Cumulative sum | `np.cumsum(arr)` |

### Axis Parameter (2D Operations)

```python
matrix = np.array([[1, 2, 3], [4, 5, 6]])

np.sum(matrix)           # 21 (sum all)
np.sum(matrix, axis=0)   # [5, 7, 9] (sum along rows — per column)
np.sum(matrix, axis=1)   # [6, 15] (sum along cols — per row)
```

> ⚠️ **Special Case — `*` is NOT matrix multiply**: `a * b` is element-wise. Use `np.dot(a, b)` or `a @ b` for matrix multiplication.

> **Data Science relevance**: Vectorized operations are 100x faster than loops. This is why NumPy is essential.

In [15]:
# --- Vectorized Operations ---
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(f"a: {a}")
print(f"b: {b}")

print(f"\nArithmetic:")
print(f"a + b: {a + b}")
print(f"a * b: {a * b}  (element-wise, NOT matrix mult)")
print(f"a ** 2: {a ** 2}")
print(f"np.sqrt(a): {np.sqrt(a)}")

# Aggregation
print(f"\nAggregation:")
print(f"np.sum(a): {np.sum(a)}")
print(f"np.mean(a): {np.mean(a)}")
print(f"np.std(a): {np.std(a):.3f}")
print(f"np.min(a): {np.min(a)}, np.max(a): {np.max(a)}")
print(f"np.argmax(a): {np.argmax(a)}  (index of max)")

# 2D with axis
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\n2D Operations:")
print(f"Matrix:\n{matrix}")
print(f"Sum all: {np.sum(matrix)}")
print(f"Sum axis=0 (per column): {np.sum(matrix, axis=0)}")
print(f"Sum axis=1 (per row): {np.sum(matrix, axis=1)}")
print(f"Mean axis=1: {np.mean(matrix, axis=1)}")

a: [1 2 3 4]
b: [5 6 7 8]

Arithmetic:
a + b: [ 6  8 10 12]
a * b: [ 5 12 21 32]  (element-wise, NOT matrix mult)
a ** 2: [ 1  4  9 16]
np.sqrt(a): [1.         1.41421356 1.73205081 2.        ]

Aggregation:
np.sum(a): 10
np.mean(a): 2.5
np.std(a): 1.118
np.min(a): 1, np.max(a): 4
np.argmax(a): 3  (index of max)

2D Operations:
Matrix:
[[1 2 3]
 [4 5 6]]
Sum all: 21
Sum axis=0 (per column): [5 7 9]
Sum axis=1 (per row): [ 6 15]
Mean axis=1: [2. 5.]


In [16]:
# --- Performance: Vectorization vs Loops ---
import numpy as np
import time

# Create large array
arr = np.random.rand(1000000)

# Method 1: Loop (slow)
start = time.time()
result_loop = [x ** 2 for x in arr]
time_loop = time.time() - start

# Method 2: NumPy vectorized (fast)
start = time.time()
result_np = arr ** 2
time_np = time.time() - start

print(f"Loop time: {time_loop*1000:.2f}ms")
print(f"NumPy time: {time_np*1000:.2f}ms")
print(f"Speedup: {time_loop/time_np:.0f}x faster with vectorization!")

Loop time: 145.11ms
NumPy time: 3.07ms
Speedup: 47x faster with vectorization!


---
## 4. Broadcasting — Operating on Different Shapes

**Broadcasting** allows NumPy to automatically align arrays of different shapes for operations.

### Broadcasting Rules

When operating on two arrays:
1. If shapes differ in number of dimensions, pad smaller with 1s on left
2. Check each dimension: either equal OR one of them is 1
3. Dimension with size 1 is "broadcast" to match the other

### Examples

```python
# Example 1: Adding scalar to array
arr = np.array([1, 2, 3])
arr + 5           # Scalar 5 broadcasts to [5, 5, 5]
                  # Result: [6, 7, 8]

# Example 2: Column + Row
col = np.array([[1], [2], [3]])    # Shape (3, 1)
row = np.array([10, 20, 30])       # Shape (3,)
col + row         # Broadcasts to (3, 3)
                  # [[1, 1, 1], [2, 2, 2], [3, 3, 3]] + [[10, 20, 30], ...]
                  # = [[11, 21, 31], [12, 22, 32], [13, 23, 33]]

# Example 3: (2, 3) + (3,)
matrix = np.array([[1, 2, 3], [4, 5, 6]])  # (2, 3)
row = np.array([10, 20, 30])               # (3,)
matrix + row      # Row broadcasts to (2, 3)
```

> ⚠️ **Special Case — Broadcasting errors**: `(3, 4) + (2, 4)` fails. Dimensions must be compatible (equal or one is 1).

> **Data Science relevance**: Normalization (subtract mean, divide by std) uses broadcasting: `(X - X.mean(axis=0)) / X.std(axis=0)` works with 2D data.

In [17]:
# --- Broadcasting Examples ---
import numpy as np

print("=== Example 1: Scalar to Array ===")
arr = np.array([1, 2, 3])
print(f"arr: {arr}")
print(f"arr + 5: {arr + 5}  (5 broadcasts to [5, 5, 5])")

print("\n=== Example 2: Row to Matrix ===")
matrix = np.array([[1, 2, 3], [4, 5, 6]])  # (2, 3)
row = np.array([10, 20, 30])               # (3,)
print(f"matrix shape: {matrix.shape}")
print(f"matrix:\n{matrix}")
print(f"\nrow: {row}, shape: {row.shape}")
print(f"\nmatrix + row:\n{matrix + row}")
print(f"(row broadcasts from (3,) to (2, 3))")

print("\n=== Example 3: Column to Matrix ===")
col = np.array([[1], [2], [3]])  # (3, 1)
row = np.array([10, 20])         # (2,)
print(f"col shape: {col.shape}")
print(f"col:\n{col}")
print(f"\nrow: {row}, shape: {row.shape}")
print(f"\ncol + row:\n{col + row}")
print(f"(Broadcasts to (3, 2))")

print("\n=== Example 4: Centering Data ===")
# Practical: normalize each column
data = np.array([[1, 100], [2, 200], [3, 300]])
print(f"Original data:\n{data}")
mean = np.mean(data, axis=0)
print(f"\nMean: {mean}")
centered = data - mean  # Broadcasting!
print(f"Centered (data - mean):\n{centered}")

=== Example 1: Scalar to Array ===
arr: [1 2 3]
arr + 5: [6 7 8]  (5 broadcasts to [5, 5, 5])

=== Example 2: Row to Matrix ===
matrix shape: (2, 3)
matrix:
[[1 2 3]
 [4 5 6]]

row: [10 20 30], shape: (3,)

matrix + row:
[[11 22 33]
 [14 25 36]]
(row broadcasts from (3,) to (2, 3))

=== Example 3: Column to Matrix ===
col shape: (3, 1)
col:
[[1]
 [2]
 [3]]

row: [10 20], shape: (2,)

col + row:
[[11 21]
 [12 22]
 [13 23]]
(Broadcasts to (3, 2))

=== Example 4: Centering Data ===
Original data:
[[  1 100]
 [  2 200]
 [  3 300]]

Mean: [  2. 200.]
Centered (data - mean):
[[  -1. -100.]
 [   0.    0.]
 [   1.  100.]]


---
## 5. Linear Algebra

NumPy provides linear algebra operations in `np.linalg` module.

### Matrix Operations

| Operation | Syntax | Notes |
|-----------|--------|-------|
| **Dot product** | `np.dot(a, b)` or `a @ b` | Matrix/vector multiplication |
| **Transpose** | `a.T` or `np.transpose(a)` | Flip rows/columns |
| **Determinant** | `np.linalg.det(a)` | Only for square matrices |
| **Inverse** | `np.linalg.inv(a)` | A × A⁻¹ = I |
| **Rank** | `np.linalg.matrix_rank(a)` | Number of independent rows/cols |
| **Eigenvalues** | `np.linalg.eig(a)` | λ where Av = λv |
| **Solve linear system** | `np.linalg.solve(A, b)` | Solves Ax = b |

### Common Patterns

```python
# Vector dot product
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.dot(v1, v2)       # 1*4 + 2*5 + 3*6 = 32

# Matrix multiply
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A @ B                # Matrix multiplication

# Transpose
A.T                  # Flip rows/columns
```

> ⚠️ **Special Case — `*` vs `@`**: `A * B` is element-wise, `A @ B` is matrix multiplication.

> **Data Science relevance**: Linear regression uses `(X^T X)^-1 X^T y`. Eigenvalues for PCA. Determinants for probability.

In [18]:
# --- Linear Algebra ---
import numpy as np

print("=== Vector Operations ===")
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(f"v1: {v1}")
print(f"v2: {v2}")
print(f"np.dot(v1, v2): {np.dot(v1, v2)}  (1*4 + 2*5 + 3*6 = 32)")
print(f"v1 @ v2: {v1 @ v2}  (same, using @ operator)")

print("\n=== Matrix Operations ===")
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(f"A:\n{A}")
print(f"\nB:\n{B}")

print(f"\nA @ B (matrix multiply):\n{A @ B}")
print(f"\nA * B (element-wise):\n{A * B}")
print(f"\nA.T (transpose):\n{A.T}")

print("\n=== Matrix Properties ===")
print(f"det(A): {np.linalg.det(A):.1f}")
print(f"rank(A): {np.linalg.matrix_rank(A)}")
print(f"\nA inverse:\n{np.linalg.inv(A)}")
print(f"\nVerify: A @ A^-1 (should be identity):\n{A @ np.linalg.inv(A)}")

print("\n=== Eigenvalues (PCA, etc) ===")
eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

=== Vector Operations ===
v1: [1 2 3]
v2: [4 5 6]
np.dot(v1, v2): 32  (1*4 + 2*5 + 3*6 = 32)
v1 @ v2: 32  (same, using @ operator)

=== Matrix Operations ===
A:
[[1 2]
 [3 4]]

B:
[[5 6]
 [7 8]]

A @ B (matrix multiply):
[[19 22]
 [43 50]]

A * B (element-wise):
[[ 5 12]
 [21 32]]

A.T (transpose):
[[1 3]
 [2 4]]

=== Matrix Properties ===
det(A): -2.0
rank(A): 2

A inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]

Verify: A @ A^-1 (should be identity):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

=== Eigenvalues (PCA, etc) ===
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


---
## 6. Common Data Science Operations

Real-world patterns for data preprocessing and analysis.

In [11]:
# --- Data Science Operations ---
import numpy as np

# Generate sample data
np.random.seed(42)  # Reproducible
data = np.random.randn(100, 3)  # 100 samples, 3 features (normal distribution)

print(f"Data shape: {data.shape}")
print(f"First 5 rows:\n{data[:5]}")

print("\n=== Standardization (Mean=0, Std=1) ===")
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)
standardized = (data - mean) / std  # Broadcasting!

print(f"Original - mean: {np.mean(data, axis=0)}")
print(f"Original - std: {np.std(data, axis=0)}")
print(f"Standardized - mean: {np.mean(standardized, axis=0)}")
print(f"Standardized - std: {np.std(standardized, axis=0)}")

print("\n=== Min-Max Normalization (0-1) ===")
min_val = np.min(data, axis=0)
max_val = np.max(data, axis=0)
normalized = (data - min_val) / (max_val - min_val)

print(f"Normalized min: {np.min(normalized, axis=0)}")
print(f"Normalized max: {np.max(normalized, axis=0)}")

print("\n=== Correlation Matrix ===")
corr_matrix = np.corrcoef(data.T)
print(f"Correlation (3x3):\n{corr_matrix}")

print("\n=== Distance Calculations ===")
# Euclidean distance between two points
p1 = np.array([0, 0])
p2 = np.array([3, 4])
distance = np.linalg.norm(p1 - p2)
print(f"Distance between {p1} and {p2}: {distance}")

print("\n=== Sorting ===")
arr = np.array([3, 1, 4, 1, 5])
print(f"Original: {arr}")
print(f"Sorted: {np.sort(arr)}")
print(f"Indices that would sort: {np.argsort(arr)}")

Data shape: (100, 3)
First 5 rows:
[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]]

=== Standardization (Mean=0, Std=1) ===
Original - mean: [ 0.09176598 -0.18323331  0.07482166]
Original - std: [0.82066472 0.97419224 1.10733139]
Standardized - mean: [-2.60902411e-17  1.55431223e-17 -8.88178420e-18]
Standardized - std: [1. 1. 1.]

=== Min-Max Normalization (0-1) ===
Normalized min: [0. 0. 0.]
Normalized max: [1. 1. 1.]

=== Correlation Matrix ===
Correlation (3x3):
[[ 1.         -0.04863585 -0.12070741]
 [-0.04863585  1.         -0.12376394]
 [-0.12070741 -0.12376394  1.        ]]

=== Distance Calculations ===
Distance between [0 0] and [3 4]: 5.0

=== Sorting ===
Original: [3 1 4 1 5]
Sorted: [1 1 3 4 5]
Indices that would sort: [1 3 0 2 4]


In [ ]:
# --- Practical ML Example: Gradient Descent ---
import numpy as np

# Simple linear regression with gradient descent
np.random.seed(42)

# Generate data: y = 2x + 3 + noise
X = np.linspace(0, 10, 50).reshape(-1, 1)
y = 2 * X.flatten() + 3 + np.random.randn(50) * 2

print(f"Data: X shape {X.shape}, y shape {y.shape}")

# Initialize parameters
m = 0.0  # Slope
b = 0.0  # Intercept
learning_rate = 0.01
iterations = 100
n = len(X)

# Gradient descent
for i in range(iterations):
    # Predictions
    y_pred = m * X.flatten() + b
    
    # Gradients
    dm = -2 / n * np.sum(X.flatten() * (y - y_pred))
    db = -2 / n * np.sum(y - y_pred)
    
    # Update
    m -= learning_rate * dm
    b -= learning_rate * db
    
    if i % 25 == 0:
        mse = np.mean((y - y_pred) ** 2)
        print(f"Iteration {i}: m={m:.3f}, b={b:.3f}, MSE={mse:.3f}")

print(f"\nFinal: y = {m:.3f}x + {b:.3f}")
print(f"(True: y = 2x + 3)")

---
## 7. Practice Exercises

Master NumPy with realistic data science problems.

### Exercise 1: Array Manipulation
1. Create a 5×5 array of random integers (0-100)
2. Replace all values > 50 with -1
3. Compute mean, median, std of each column
4. Reshape to (5, 5) then flatten back
5. Find indices of max value

In [ ]:
# Exercise 1: Array Manipulation
import numpy as np

# Your code here:

### Exercise 2: Broadcasting and Filtering
1. Create a 4×3 matrix and a 1D array [10, 20, 30]
2. Subtract the array from each row (broadcasting)
3. Filter rows where the first column > 0
4. Calculate mean of filtered data
5. Normalize filtered data to [0, 1]

In [ ]:
# Exercise 2: Broadcasting and Filtering
import numpy as np

# Your code here:

### Exercise 3: Statistical Analysis
1. Create 1000 samples from normal distribution (mean=100, std=15)
2. Calculate z-scores: (x - mean) / std
3. Find values within ±2 std (68% of data)
4. Create histogram of original vs z-scores
5. Count outliers (|z-score| > 3)

In [ ]:
# Exercise 3: Statistical Analysis
import numpy as np

# Your code here:

### Exercise 4: Matrix Operations
1. Create two 3×3 matrices A and B
2. Compute A @ B, A.T, det(A)
3. Check if A is invertible (det ≠ 0)
4. Verify A @ A^-1 ≈ Identity
5. Solve system Ax = b for random b

In [ ]:
# Exercise 4: Matrix Operations
import numpy as np

# Your code here:

### Exercise 5: Data Standardization Pipeline
1. Generate random dataset (100 samples, 4 features)
2. Split into train (80) and test (20)
3. Standardize using train statistics (mean, std)
4. Apply same standardization to test
5. Verify train mean≈0, std≈1; test similar but not exact

In [ ]:
# Exercise 5: Data Standardization Pipeline
import numpy as np

# Your code here:

---
## 📝 Session 7 Summary

### What You Learned

| Topic | Key Takeaway |
|-------|---------------|
| **Arrays** | NumPy arrays are fast, typed, and homogeneous — foundational for all data science |
| **Indexing/Slicing** | 1D and 2D indexing; boolean masking for filtering |
| **Vectorization** | Operations on whole arrays without loops — 100x+ faster |
| **Broadcasting** | Automatic alignment of different shapes — elegant data manipulation |
| **Linear Algebra** | Dot products, transposes, inverses, eigenvalues — basis of ML math |
| **Operations** | Aggregations (sum, mean, std), axis parameter, sorting |
| **Standardization** | Normalize data with broadcasting — essential preprocessing |

### Key Gotchas to Remember
- Arrays have fixed type — can't mix int and float without conversion
- `arr2 = arr` shares data (view), use `arr.copy()` for independence
- Slices return views — modifications affect original
- `*` is element-wise multiply, `@` is matrix multiply
- Broadcasting requires compatible dimensions (equal or one is 1)
- `axis=0` operates along rows (reduces rows), `axis=1` along columns
- Aggregation functions have `keepdims` parameter for shape preservation

### Data Science Superpowers
- **Vectorized operations** — Write ML algorithms without explicit loops
- **Broadcasting** — Elegant data preprocessing (normalization, centering)
- **Linear algebra** — Implement regression, PCA, SVD
- **Indexing** — Complex filtering and fancy indexing
- **Performance** — NumPy is 100-1000x faster than Python loops

### Next Session
**Session 8**: NumPy Advanced & Introduction to Pandas — Moving from arrays to DataFrames for tabular data analysis.